apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mebw44jc5-go 
  janus-idp.io/tekton: mebw44jc5-go
  backstage.io/kubernetes-id: mebw44jc5-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mebw44jc5-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml